server:
  port: 8099

dubbo:
  application:
    name: "order-service0-impl"
  # 注册中心
  registry:
    # 指定注册中心为redis
    protocol: redis
    # root是随便写的 后面跟的是密码 和redis host以及port
    address: root:YX19980904@192.144.220.234:6379
    # 指定分区环境
    parameters:
      namespace: dubbo-rpc
    password: YX19980904
  protocol:
    name: dubbo
    port: -1
  scan:
    base-packages:
      - com.cqnews.rpc.service.impl
# nacos 配置中心
nacos:
  discovery:
    server-addr: 192.144.220.234:8848